FROM golang:1.23.1-alpine as builder

RUN apk add --no-cache make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build-consumer

# --------------------------------

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/bin/consumer .
EXPOSE 3001
CMD ["./consumer"]