// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/WsDev69/producer-consumer/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Process provides a mock function with given fields: ctx, taskRequest
func (_m *Client) Process(ctx context.Context, taskRequest model.TaskRequest) error {
	ret := _m.Called(ctx, taskRequest)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TaskRequest) error); ok {
		r0 = rf(ctx, taskRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
