// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: tasks_sums.sql

package sqlc

import (
	"context"
)

const getTotalValueByTaskType = `-- name: GetTotalValueByTaskType :one
SELECT task_type, total_value FROM task_sums
WHERE task_type = $1
`

func (q *Queries) GetTotalValueByTaskType(ctx context.Context, taskType int32) (TaskSum, error) {
	row := q.db.QueryRow(ctx, getTotalValueByTaskType, taskType)
	var i TaskSum
	err := row.Scan(&i.TaskType, &i.TotalValue)
	return i, err
}
